version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - flask
    ports:
      - "443:443"
  flask:
    build: ./flask
    environment:
      FLASK_ENV: development
      SESSION_SECRET: $SESSION_SECRET
    expose:
      - "8080"
  redis:
    image: "redis:alpine"